package com.mark.humanbody;

/**
 * Created by Mark on 2/20/2017.
 */

public class bodyImages {

    public static int[] AuditorySystem = new int[]{R.drawable.cochlea, R.drawable.incus, R.drawable.malleus, R.drawable.stapes, R.drawable.tymphanicmembrane};
    public static int[] CirculatorySystem = new int[]{R.drawable.abdominalaorta, R.drawable.anteriortibialartery, R.drawable.axillaryartery, R.drawable.axillaryvein, R.drawable.basilicvein, R.drawable.brachialartery, R.drawable.brachialveins, R.drawable.brachiocephalicartery, R.drawable.cephalicvein, R.drawable.commoncarotidartery, R.drawable.commoniliacartery, R.drawable.commoniliacvein, R.drawable.deeparteryofthethigh, R.drawable.externalcarotidartery, R.drawable.externaliliacartery, R.drawable.externaliliacvein, R.drawable.femoralartery, R.drawable.femoralvein, R.drawable.fibularartery, R.drawable.fibularvein, R.drawable.greatsaphenousvein, R.drawable.heart, R.drawable.internalcarotidartery, R.drawable.internaliliacartery, R.drawable.internaliliacvein, R.drawable.internaljugularvein, R.drawable.mediancubitalvein, R.drawable.poplitealartery, R.drawable.poplitealvein, R.drawable.posteriortibialartery, R.drawable.radialartery, R.drawable.renalartery, R.drawable.renalvein, R.drawable.subclavianartery, R.drawable.subclavianvein, R.drawable.ulnarartery};
    public static int[] DigestiveSystem = new int[]{R.drawable.anus, R.drawable.appendix, R.drawable.ascendingcolon, R.drawable.duodenum, R.drawable.esophagus, R.drawable.gallbladder, R.drawable.genioglossus, R.drawable.hardpalate, R.drawable.hyoidbone, R.drawable.largeintestine, R.drawable.lip, R.drawable.liver, R.drawable.pancreas, R.drawable.rectum, R.drawable.smallintestine, R.drawable.spleen, R.drawable.stomach, R.drawable.thyroidcartilage, R.drawable.tongue, R.drawable.trachea, R.drawable.transversecolon};
    public static int[] EndocrineSystem = new int[]{R.drawable.adrenalgland, R.drawable.hypothalamus, R.drawable.parathyroidgland, R.drawable.pinealgland, R.drawable.pituitarygland, R.drawable.thymusgland, R.drawable.thyroidgland};
    public static int[] ImmuneLymphaticSystem = new int[]{R.drawable.axillarynode, R.drawable.cervicalnodes, R.drawable.cubitalnode, R.drawable.cysternachili, R.drawable.iliacnodes, R.drawable.intestinaltrunk, R.drawable.lingualtonsil, R.drawable.lumbartrunk, R.drawable.palatinetonsil, R.drawable.peyerspatch, R.drawable.thoracicduct};
    public static int[] IntegumentarySystem = new int[]{R.drawable.dermis, R.drawable.eccrinesweatgland, R.drawable.epidermis, R.drawable.hair, R.drawable.hairfollicle, R.drawable.nerve, R.drawable.sebaciousgland, R.drawable.skin, R.drawable.subcutislayer};
    public static int[] NervousSystem = new int[]{R.drawable.brain, R.drawable.lumbarnerve, R.drawable.plantaldigitalnerve, R.drawable.sacralnerve, R.drawable.saphenousnerve, R.drawable.sciaticnerve, R.drawable.spinalcord, R.drawable.suralnerve, R.drawable.thoracicnerve};
    public static int[] ReproductiveSystem_female = new int[]{R.drawable.cervicalcanal, R.drawable.endometrium, R.drawable.fallopiantube, R.drawable.fundus, R.drawable.ovarianligament, R.drawable.ovary, R.drawable.uterus, R.drawable.vagina};
    public static int[] ReproductiveSystem_male = new int[]{R.drawable.epididymis, R.drawable.penis, R.drawable.prostategland, R.drawable.seminalvesicle, R.drawable.testes, R.drawable.vasdeferens};
    public static int[] RespiratorySystem = new int[]{R.drawable.diaphragm, R.drawable.frontalsinus, R.drawable.larynx, R.drawable.lung, R.drawable.maxillarysinus, R.drawable.mouth, R.drawable.nasopharynx, R.drawable.orapharynx, R.drawable.trachea};
    public static int[] SkeletalSystem = new int[]{R.drawable.calcaneus, R.drawable.clavicle, R.drawable.cuboidbone, R.drawable.falseribs, R.drawable.fibula, R.drawable.hamatebone, R.drawable.humerus, R.drawable.ilium, R.drawable.lunatebone, R.drawable.metatarsalbone, R.drawable.navicularbone, R.drawable.patella, R.drawable.radius, R.drawable.scaphoidbone, R.drawable.scapula, R.drawable.skull, R.drawable.spine, R.drawable.sternum, R.drawable.talus, R.drawable.teeth, R.drawable.tibia, R.drawable.trueribs, R.drawable.ulna};
    public static int[] UrinarySystem = new int[]{R.drawable.kidney, R.drawable.ureter, R.drawable.urethra, R.drawable.urinarybladder};

    public static String[] AuditorySystem_name = new String[]{"Cochlea", "Incus", "Malleus", "Stapes", "Tymphanic membrane"};
    public static String[] CirculatorySystem_name = new String[]{"Abdominal aorta", "Anterior tibial artery", "Axillary artery", "Axillary vein", "Basilic vein", "Brachial artery", "Brachial veins", "Brachiocephalic artery", "Cephalic vein", "Common carotid artery", "Common iliacartery", "Commoniliac vein", "Deep artery of the thigh", "External carotid artery", "External iliac artery", "External iliac vein", "Femoral artery", "Femoral vein", "Fibular artery", "Fibular vein", "Great saphenous vein", "Heart", "Internal carotida rtery", "Internal iliac artery", "Internal iliac vein", "Internal jugular vein", "Median cubital vein", "Popliteal artery", "Poplitea lvein", "Posterior tibial artery", "Radial artery", "Renal artery", "Renal vein", "Subclavian artery", "Subclavian vein", "Ulnar artery"};
    public static String[] DigestiveSystem_name = new String[]{"Anus", "Appendix", "Ascending colon", "Duodenum", "Esophagus", "Gallbladder", "Genioglossus", "Hard palate", "Hyoid bone", "Large intestine", "Lip", "Liver", "Pancreas", "Rectum", "Small intestine", "Spleen", "Stomach", "Thyroid cartilage", "Tongue", "Trachea", "Transverse colon"};
    public static String[] EndocrineSystem_name = new String[]{"Adrenal gland", "Hypothalamus", "Parathyroid gland", "Pineal gland", "Pituitary gland", "Thymus gland", "Thyroid gland"};
    public static String[] ImmuneLymphaticSystem_name = new String[]{"Axillary node", "Cervical nodes", "Cubital node", "Cysterna chili", "Iliac nodes", "Intestinal trunk", "Lingual tonsil", "Lumbar trunk", "Palatine tonsil", "Peyers patch", "Thoracic duct"};
    public static String[] IntegumentarySystem_name = new String[]{"Dermis", "Eccrine sweat gland", "Epidermis", "Hair", "Hairfollicle", "Nerve", "Sebacious gland", "Skin", "Subcutis layer"};
    public static String[] NervousSystem_name = new String[]{"Brain", "Lumbar nerve", "Plantal digital nerve", "Sacral nerve", "Saphenous nerve", "Sciatic nerve", "Spinal cord", "Sural nerve", "Thoracic nerve"};
    public static String[] ReproductiveSystem_female_name = new String[]{"Cervical canal", "Endometrium", "Fallopian tube", "Fundus", "Ovarian ligament", "Ovary", "Uterus", "Vagina"};
    public static String[] ReproductiveSystem_male_name = new String[]{"Epididymis", "Penis", "Prostate gland", "Seminal vesicle", "Testes", "Vasdeferens"};
    public static String[] RespiratorySystem_name = new String[]{"Diaphragm", "Frontal sinus", "Larynx", "Lung", "Maxillary sinus", "Mouth", "Nasopharynx", "Orapharynx", "Trachea"};
    public static String[] SkeletalSystem_name = new String[]{"Calcaneus", "Clavicle", "Cuboid bone", "Falseribs", "Fibula", "Hamate bone", "Humerus", "Ilium", "Lunate bone", "Metatarsal bone", "Navicular bone", "Patella", "Radius", "Scaphoid bone", "Scapula", "Skull", "Spine", "Sternum", "Talus", "Teeth", "Tibia", "True ribs", "Ulna"};
    public static String[] UrinarySystem_name = new String[]{"Kidney", "Ureter", "Urethra", "Urinary Bladder"};

    public static String[] allBodySystem_name = new String[]{"cochlea", "incus", "malleus", "stapes", "tymphanic membrane", "abdominal aorta", "anterior tibial artery", "axillary artery", "axillary vein", "basilic vein", "brachial artery", "brachial veins", "brachiocephalic artery", "cephalic vein", "common carotid artery", "common iliacartery", "commoniliac vein", "deep artery of the thigh", "external carotid artery", "external iliac artery", "external iliac vein", "femoral artery", "femoral vein", "fibular artery", "fibular vein", "great saphenous vein", "heart", "internal carotida rtery", "internal iliac artery", "internal iliac vein", "internal jugular vein", "median cubital vein", "popliteal artery", "poplitea lvein", "posterior tibial artery", "radial artery", "renal artery", "renal vein", "subclavian artery", "subclavian vein", "ulnar artery", "anus", "appendix", "ascending colon", "duodenum", "esophagus", "gallbladder", "genioglossus", "hard palate", "hyoid bone", "large intestine", "lip", "liver", "pancreas", "rectum", "small intestine", "spleen", "stomach", "thyroid cartilage", "tongue", "trachea", "transverse colon", "adrenal gland", "hypothalamus", "parathyroid gland", "pineal gland", "pituitary gland", "thymus gland", "thyroid gland", "axillary node", "cervical nodes", "cubital node", "cysterna chili", "iliac nodes", "intestinal trunk", "lingual tonsil", "lumbar trunk", "palatine tonsil", "peyers patch", "thoracic duct", "dermis", "eccrinesweat gland", "epidermis", "hair", "hairfollicle", "nerve", "sebacious gland", "skin", "subcutis layer", "brain", "lumbar nerve", "plantal digital nerve", "sacral nerve", "saphenous nerve", "sciatic nerve", "spinal cord", "sural nerve", "thoracic nerve", "cervical canal", "endometrium", "fallopian tube", "fundus", "ovarian ligament", "ovary", "uterus", "vagina", "epididymis", "penis", "prostate gland", "seminal vesicle", "testes", "vas deferens", "diaphragm", "frontalsinus", "larynx", "lung", "maxillarysinus", "mouth", "nasopharynx", "orapharynx", "trachea", "calcaneus", "clavicle", "cuboid bone", "false ribs", "fibula", "hamate bone", "humerus", "ilium", "lunate bone", "metatarsal bone", "navicular bone", "patella", "radius", "scaphoid bone", "scapula", "skull", "spine", "sternum", "talus", "teeth", "tibia", "true ribs", "ulna", "kidney", "ureter", "urethra", "urinary bladder"};
    public static int[] allBodySystem_index = new int[]{1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12};
    public static int[] allBodySystem_no = new int[]{1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 31, 33, 34, 35, 36, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 1, 2, 3, 4};
    public static String[] AuditorySystem_value = new String[]{
            "\tthe spiral cavity of the inner ear containing the organ of Corti, which produces nerve impulses in response to sound vibrations.",
            "\tis a bone in the middle ear. The anvil-shaped small bone is one of three ossicles in the middle ear. The incus receives vibrations from the malleus, to which it is connected laterally, and transmits these to the stapes, medially. The incus is so-called because of its resemblance to an anvil (Latin: Incus).",
            "\tis a hammer-shaped small bone or ossicle of the middle ear which connects with the incus and is attached to the inner surface of the eardrum. The word is Latin for hammer or mallet. It transmits the sound vibrations from the eardrum to the incus.",
            "\tis a bone in the middle ear of humans and other mammals which is involved in the conduction of sound vibrations to the inner ear. The stirrup-shaped small bone is on and transmits these to the oval window, medially. The stapes is the smallest and lightest named bone in the human body, and is so-called because of its resemblance to a stirrup.",
            "\ta membrane forming part of the organ of hearing, which vibrates in response to sound waves. In humans and other higher vertebrates it forms the eardrum, between the outer and middle ear.",
    };
    public static String[] CirculatorySystem_value = new String[]{
            "\tThe abdominal aorta is the largest artery in the abdominal cavity. As part of the aorta, it is a direct continuation of the descending aorta (of the thorax).",
            "\tThe anterior tibial artery  of the leg carries blood to the anterior compartment of the leg and dorsal surface of the foot, from the popliteal artery. It is accompanied the anterior tibial vein, along its course. It crosses the anterior aspect of the ankle joint, at which point it becomes the dorsalis pedis artery.",
            "\tIn human anatomy the axillary artery is a large blood vessel that conveys oxygenated blood to the lateral aspect of the thorax, the axilla(armpit) and the upper limb. Its origin is at the lateral margin of the first rib, before which it is called the subclavian artery. After passing the lower margin of teres major it becomes the brachial artery.",
            "\tIn human anatomy the axillary artery is a large blood vessel that conveys oxygenated blood to the lateral aspect of the thorax, the axilla(armpit) and the upper limb. Its origin is at the lateral margin of the first rib, before which it is called the subclavian artery. After passing the lower margin of teres major it becomes the brachial artery.",
            "\tThe basilic vein is a large superficial vein of the upper limb that helps drain parts of the hand and forearm. It originates on the medial (ulnar) side of the dorsal venous network of the hand and travels up the base of the forearm, where its course is generally visible through the skin as it travels in the subcutaneous fat and fascia lying superficial to the muscles.",
            "\tThe brachial artery  is the major blood vessel of the (upper) arm. It is the continuation of the axillary artery beyond the lower margin of teres major muscle. It continues down the ventral surface of the arm until it reaches the cubital fossa at the elbow. It then divides into the radial and ulnar arteries which run down the forearm. In some individuals, the bifurcation occurs much earlier and the ulnar and radial arteries extend through the upper arm. The pulse of the brachial artery is palpable on the anterior aspect of the elbow, medial to the tendon of the biceps, and, with the use of a stethoscope and sphygmomanometer(blood pressure cuff) often used to measure the blood pressure.",
            "\tIn human anatomy, the brachial veins are venae comitantes of the brachial artery in the arm proper. Because they are deep to muscle, they are considered deep veins. Their course is that of the brachial artery (in reverse): they begin where radial veins and ulnar veins join(corresponding to the bifurcation of the brachial artery). They end at the inferior border of the teres major muscle. At this point, the brachial veins join the basilic vein to form the axillary vein.",
            "\tThe brachiocephalic artery(or brachiocephalic trunk or innominate artery) is an artery of the mediastinum that supplies blood to the right arm and the head and neck. It is the first branch of the aortic arch, and soon after it emerges, the brachiocephalic artery divides into the right common carotid artery and the right subclavian artery.",
            "\tIn human anatomy, the cephalic vein (also known as the antecubital vein) is a superficial vein in the arm. It communicates with the basilic vein via the median cubital vein at the elbow and is located in the superficial fascia along the anterolateral surface of the biceps brachii muscle.",
            "\tIn anatomy, the left and right common carotid arteries are arteries that supply the head and neck with oxygenated blood they divide in the neck to form the external and internal carotid arteries.",
            "\tThe common iliac arteries are two large arteries that originate from the aortic bifurcation at the level of the fourth lumbar vertebra. They end in front of  the sacroiliac joint, one on either side, and each bifurcates into the external and internal iliac arteries.",
            "\tIn human anatomy, the common iliac veins are formed by the external iliac veins and internal iliac veins. The Left and right common iliac veins come together in the abdomen at the level of the fifth lumbar vertebra, forming the inferior vena cava. They drain blood from the pelvis and lower limbs.",
            "\tThe deep artery of the thigh (profunda femoris artery or deep femoral artery) is a branch of the femoral artery that, as its name suggests, travels more deeply(posteriorly) than the rest of the femoral artery.",
            "\tThe external carotid artery is a major artery of the head and neck. It arises from the common carotid artery when it splits into the external and internal carotid artery. It supplies blood to the face and neck.",
            "\tThe external iliac artery are two major arteries which bifurcate off the common iliac arteries anterior to the sacroiliac joint of the pelvis. They proceed anterior and inferior along the medial border of the psoas major muscles. They exit the pelvis girdle posterior and inferior to the inguinal ligament about one third laterally from the insertion point of the inguinal ligament on the public tubercle at which pointthey are reffered to as the femoral arteries. The external iliac artery is usually the artery used to attach the renal artery to the recipient of a kidney transplant.",
            "\tThe external iliac vein are large veins that connect the femoral veins to the common iliac veins. Their origin is at the inferior margin of the inguinal ligaments and they terminate when they join the internal iliac veins(to form the common iliac veins). Both external iliac veins are accompanied along their course by external iliac arteries.",
            "\tThe femoral artery is a large artery in the thigh and the main arterial supply to the lower limb. It entries the thigh from behind the inguinal ligament as the common femoral artery, a continuation of the external iliac artery.",
            "\tIn the human anatomy, the femoral vein is  a blood vessel that accompanies the femoral artery in the femoral sheath. It begins at the adductor canal (also known as hunter's canal) and is a continuation of the popliteal vein. It ends at the inferior margin of the inguinal ligament,where it becomes the external iliac veins.",
            "\tIn anatomy, the fibular artery(also known as the peroneal artery) supplies blood to the lateral compartment of the leg. It arises from the tibal fibular trunk.",
            "\tIn anatomy, the fibular veins(also known as the peroneal veins) are accompanying veins (venae comitantes) of the fibular artery.",
            "\tThe great saphenous vein(GSV),previously also called the long saphenous vein, is a large, subcutaneous,superficial vein of the leg.It is the longest vein in the body running along the length of the lower limb.",
            "\tThe heart is a muscular organ in humans and other animals, which pumps blood through the blood vessels of the circulatory system.Blood provides the body with oxygen and nutrients, as well as assists in the removal of metabolic wastes.The heart is located in the middle compartment of the chest.",
            "\tThe internal carotid artery is a major paired artery, one on each side of the head and neck, In human anatomy. They arise from the common carotid arteries where these bifurcate into the internal and external carotid arteries at cervical vertebral level 3 or 4; the internal carotid artery supplies the brain, while the external carotid nourishes other portions of the head, such as face, scalp, skull, and meninges.",
            "\tThe internal iliac artery (formerly known as the hypogastric artery) is the main artery of the pelvis.",
            "\tThe Internal iliac vein (hypogastric vein) begins near the upper part of the greater sciatic foramen, passes upward behind and slightly medial to the internal iliac artery and, at the brim of the pelvis, joins with the external iliac vein to form the common iliac vein.",
            "\tThe internal jugular vein is a paired jugular vein that collects blood from the brain and the superficial parts of the face and neck.The vein runs in the carotid sheath with the common carotid artery and vagus nerve.",
            "\tIn human anatomy, the median cubital vein (or median basilic vein) is a superficial vein of the upper limb.It connects the basilica and cephalic vein and is often used for venipuncture(taking blood) It lies in the cubital fossa superficial to the bicipital aponeurosis.",
            "\tThe popliteal artery is a deeply placed continuation of the femoral artery after it passes through the adductor hiatus, or opening in the distal portion of the adductor magnus muscle. It courses through the popliteal fossa and ends at the lower border of the popliteus muscle,where it branches into the anterior and posterior tibial arteries.",
            "\tThe popliteal vein is formed by the junction of the venae comitantes of the anterior and posterior tibal vein at the lower border of the popliteus muscle on the medial side of the popliteal artery. As it ascends through the fossa, it crosses behind the popliteal artery so that it comes to lie on its lateral side. It passes through the opening in the adductor magnus to become the femoral vein.",
            "\tThe Posterior tibial artery of the lower limb carries blood to the posterior compartment of the leg and plantar surface of the foot from the popliteal artery via the tibial-fibular trunk.It is accompanied by a deep vein, the posterior tibial vein, along its course.",
            "\tIn human anatomy,the radial artery is the main artery of the lateral aspect of the forearm.",
            "\tThe Renal artery normally arise off the side of the abdominal aorta, immediately below the superior mesenteric artery, and supply the kidneys with blood. Each is directed across the crus of the diaphragm, so as to form nearly a right angle with the aorta. The renal arteries carry a large portion of total blood flow to the kidneys. Up to a third of total cardiac output can pass through the renal arteries to be filtered by the kidneys.",
            "\tThe renal veins are veins that drain the kidney. They connect the kidney to the inferior vena cava. They carry the blood filtered by the kidney.",
            "\tIn human anatomy, the subclavian arteries are paired major arteries of the upper thorax, below the clavicle.They receive blood from the aortic arch. The left subclavian artery supplies blood to the left arm and the right subclavian artery supplies blood to the right arm, with some branches supplying the head and thorax.On the left side of the body, the subclavian comes directly off the arch of aorta, while on the right side it arises from the relatively short brachiocephalic artery when it bifurcates into the subclavian and the right common carotid artery.",
            "\tThe Subclavian vein is a paired large vein, one on either side of the body. Their diameter is approximately that of the smallest finger.",
            "\tThe ulnar artery is the main blood vessel, with oxygenated blood, of the medial aspect of the forearm. It arises from the brachial artery and terminates in the superficial palmar arch, which joins with the superficial branch of the radial artery. It is palpable on the anterior and medial aspect of the wrist.",

    };


    public static String[] DigestiveSystem_value = new String[]{
            "\tThe anus is an opening at the opposite end of an animal's digestive tract from the mouth. Its function is to control the expulsion of feces, unwanted semi-gold matter produced during digestion, which, depending on the type of animal, may include: matter which the animal cannot digest, such as bones; food material after all the nutrients have been extracted, for example cellulose or lignin; ingisted matter which would be toxic if it remained in the digestive tract; and dead or excess gut bacteria and other endosymbionts.",
            "\tThe appendix is a blind-ended tube connected to the cecum, from which it develops embryologically. The cecum is a pouchlike structure of the colon, located at the junction of the small and the large intestines.",
            "\tThe ascending colon is the part colon located between the cecum and the transverse colon.",
            "\tThe duodenum or dodecadactylum is the first section of the small intestine in most higher vertebrates, including mammals, reptiles, and birds.",
            "\tThe esophagus or esophagus, commonly known as the food pipe or gullet, is an organ in vertebrates through which food passes, aided by peristaltic contractions, from the pharynx to the stomach. The esophagus is a fibromuscular tube, about 25 centimetres long in adults, which travels behind the trachea and heart, passes through the diaphragm and empties into the uppermost region of the stomach. During swallowing, the epiglottis tilts backwards to prevent food from going down the larynx and lungs.",
            "\tIn vertabrates the gallbladder is a small organ where bile (a fluid produced by the liver) is stored and concentrated before it is released into the small intestine.",
            "\tThe genioglossus is one of the paired extrinsic muscle of the tongue. The genioglossus is the major muscle responsible for protruding (or sticking out) the tongue.",
            "\tThe hard palate is a thin horizontal bony plate of the skull, located in the roof of the mouth. It is formed by the palatine process of the maxilla and horizontal plate of palatine bone, and spans the arch formed by the upper teeth.",
            "\tThe hyoid bone is a horseshoe-shaped bone situated in the anterior midline of the neck between the chin and the thyroid cartilage. At rest, it lies at the level of the base of the mandible in the front and the third cervical vertebra (C3) behind.",
            "\tThe large intestine or the large bowel, is the last part of the gastrointestinal tract and of the digestive system in vertebrates. Water is absorb here and the remaining waste material is stored as feces before being by defecation.",
            "\tLips are a visible body part at the mouth of humans and many animals. Lips are soft, movable and serve as the opening for food intake and in the articulation of sound and speech. Human lips are a tactile sensory organ and can be an erogenous zone when used in kissing and other acts of intimacy.",
            "\tThe liver is a vital organ of vertebrates and some other animals. In the human, it is located in the upper right quadrant of the abdomen, below the diaphragm. The liver has awide range of functions, including detoxification of various metabolites, protein, synthesis, and the production of biochemicals necessary for digestion.",
            "\tThe pancreas is a glandular organ in the digestive system and endocrine system of vertebrates. In human, it is located in the abdominal cavity behind the stomach. It is an endocrine gland producing several important hormones, including insulin, glucagon, somatostatin, and pancreatic polypeptide which circulate blood.",
            "\tThe rectum is the final straight portion of the large intestine in some mammals, and the gut in others. The human rectume is about 12 centimeters (4.7 in ) long, and begins at the rectosigmoid junction ( the end of the sigmoid colon ), at the level of the third sacral vertebra or the sacral promontory depending upon what definition is used.",
            "\tThe small intestine or small bowel is the part of the gastrointestinal tract between the stomach and the large intestine, and is where most of the end absorption of food takes place. The small intestine has three distinct regions - the doudenum, jejunum, and ileum. \n",
            "\tThe spleen is an organ found in virtuality all vertebrates. Similar in structure to a large lymph nod. It acts primary as a blood filter. The spleen plays important roles in regard to red blood celss and the immune system.",
            "\tThe stomach is a muscular, hollow, dillated part of the gastrointetsinal tract that functions as an important organ in the digestive system. The stomach is present in many animals including vertebrates, echinoderms, insects, and molluscs.",
            "\tThe thyroid cartilage is the largest of the nine cartilages that make up the laryngeal skeleton, the cartilage structure in and around the trachea that contains the larynx. It does not completely encircle the larynx, only the cricoid cartilage does.",
            "\tThe tongue is a muscular organ in the mouth of most vertebrates that manipulates food for mastication, and is used in the acr of swallowing. It is of important in the digestive system and is the primary organ of taste in the gustatory system. ",
            "\tThe trachea, colloquially caleed the windpipe, is a cartilaginous tube that connects the pharynx and larynx to the lungs, allowing the passage air, and so is present in almost all air- breathing animals with lungs.",
            "\tThe transverse colon is the longest and most movable part of the colon. It crosses the abdomen from the ascending colon at  the hepatic or right colic flexure with a downward convexity to the descending colon where it curves sharply on itself beneath the lower end of the spleen forming the splenic or left colic flexure.",

    };
    public static String[] EndocrineSystem_value = new String[]{
            "\tare endocrine glands that produce a variety of hormones including adrenaline and the steroids aldosterone and cortisol. They are found above the kidneys. Each gland has an outer cortex which produces steroid hormones and an inner medulla. The adrenal cortex itself is divided into three zones: zona glomerulosa, the zona fasciculata and the zona reticularis.",
            "\tis a portion of the brain that contains a number of small nuclei with a variety of functions. One of the most important functions of the hypothalamus is to link the nervous system to the endocrine system via the pituitary gland (hypophysis). https://en.wikipedia.org/wiki/Hypothalamus",
            "\tare small endocrine glands in the neck of humans and other tetrapods that produce parathyroid hormone. Humans usually have four parathyroid glands, variably located on the back of the thyroid gland - considerable variation exists.Parathyroid hormone and calcitonin (one of the hormones made by the thyroid gland) have key roles in regulating the amount of calcium in the blood and within the bones.",
            "\talso known as the pineal body, conarium or epiphysis cerebri, is a small endocrine gland in the vertebratebrain. The shape of the gland resembles a pine cone, hence its name. The pineal gland is located in the epithalamus, near the center of the brain, between the two hemispheres, tucked in a groove where the two halves of the thalamus join. The pineal gland produces melatonin, a serotonin derived hormone which modulates sleep patterns in both circadian and seasonal cycles.",
            "\tis an endocrine gland about the size of a pea and weighing 0.5 grams (0.018 oz) in humans. It is a protrusion off the bottom of the hypothalamus at the base of the brain. The hypophysis rests upon the hypophysial fossa of the sphenoid bone in the center of the middle cranial fossa and is surrounded by a small bony cavity (sella turcica) covered by a dural fold (diaphragma sellae) The anterior pituitary (or adenohypophysis) is a lobe of the gland that regulates several physiological processes (including stress, growth, reproduction, and lactation). The intermediate lobe synthesizes and secretes melanocyte-stimulating hormone. The posterior pituitary (or neurohypophysis) is a lobe of the gland that is functionally connected to the hypothalamus by the median eminence via a small tube called the pituitary stalk (also called the infundibular stalk or the infundibulum).\n" +
                    "https://en.wikipedia.org/wiki/Pituitary_gland\n",
            "is a specialized primary lymphoid organ of the immune system. Within the thymus, T cells or T lymphocytes mature. T cells are critical to the adaptive immune system, where the body adapts specifically to foreign invaders. The thymus is composed of two identical lobes and is located anatomically in the anterior superior mediastinum, in front of the heart and behind the sternum. Histologically, each lobe of the thymus can be divided into a central medulla and a peripheral cortex which is surrounded by an outer capsule. The cortex and medulla play different roles in the development of T-cells. Cells in the thymus can be divided into thymic stromal cells and cells of hematopoietic origin (derived from bone marrow resident hematopoietic stem cells). Developing T-cells are referred to as thymocytes and are of hematopoietic origin. Stromal cells include epithelial cells of the thymic cortex and medulla, and dendritic cells.",
            "is an endocrine gland in the neck, and consists of two lobes connected by an isthmus. It is found at the front of the neck, below the Adam's apple. The thyroid gland secretes thyroid hormones, which primarily influence the metabolic rate and protein synthesis. The hormones also have many other effects including those on development. The thyroid hormones T3 and T4 are synthesized from iodine and tyrosine. The thyroid also produces the hormone calcitonin, which plays a role in calcium homeostasis.",
    };

    public static String[] ImmuneLymphaticSystem_value = new String[]{
            "\tThe axillary nodes are a group of lymph nodes located in the axillary (or armpit) region of the body. They perform the vital function of filtration and conduction of lymph from the upper limbs, pectoral region, and upper back.",
            "\tThe cervical nodes are one of the six major locations of lymph nodes. They are grouped along the lower border of the jaw, in front of and behind the ears, and deep in the neck along the larger blood vessels. They drain the skin of the scalp, face, tissues of the nasal cavity, and the pharynx. All lymph nodes have the primary function of the production of lymphocytes, which help defend the body against microorganisms and against harmful foreign particles and debris from lymph before it is returned to the blood stream.",
            "\tThe cubital nodes or epitrochlear nodes (also called cubital lymph nodes or cubital glands) are two sets of lymphatic nodes located near the elbow of each arm, generally just above the medial epicondyle. There is a superficial cubital node and a deep cubital node for each arm, together draining both the forearm and the hand on the ulnar side of the arm. The flow of the efferent lymphatics proceeds toward the brachial and axillary lymph nodes.",
            "\tThe cysterna chyli is also called the cisterna chyli. This is a sac which receives lymph from both of the lumbar lymphatic trunks and the intestinal trunk. It can be found at the lower end of the thoracic duct. Lymph is a milky body fluid which contains a type of white blood cells, called lymphocytes, along with proteins and fats. Lymph plays an important role in the immune system and in absorbing fats from the intestines.",
            "\tIliac nodes, including both external iliac lymph nodes and internal iliac lymph nodes, service the iliac vessels of the pelvis. There are 8-10 external iliac nodes filtering the blood and lymph of the external iliac veins and arteries, fed principally by the afferent lymphatics of the pelvis (including the upper vagina, cervix, urethra, bladder, and prostate) as well as those of the inguinal lymph nodes.",
            "\tThe intestinal trunk drains lymph from the organs of the abdominal cavity. It then joins the thoracic duct. After leaving this collecting duct, the lymph enters the veins to become part of the plasma, just before the blood returns to the right atrium of the heart.",
            "\tThe lingual tonsils are composed of lymphoid tissue, and located on the posterior area of the tongue, on the lateral base.",
            "The lumbar trunks are formed by the union of the efferent vessels from the lateral aortic lymph nodes. They receive the lymph from the lower limbs, from the walls and viscera of the pelvis, from the kidneys and suprarenal glands and the deep lymphatics of the greater part of the abdominal wall. Ultimately, the lumbar trunks empty into the cisterna chyli, a dilatation at the beginning of the thoracic duct.",
            "\tThe palatine tonsils (what the term tonsils generally refer to) are two lymphatic tissue masses. There is one located on each side of the oral pharynx, in the back of the throat. The function of palatine tonsils has yet to be discovered, however they are part of the immune",
            "\tPeyer’s patches are small masses of lymphatic tissue found throughout the ileum region of the small intestine. Also known as aggregated lymphoid nodules, they form an important part of the immune system by monitoring intestinal bacteria populations and preventing the growth of pathogenic bacteria in the intestines.",
            "\tThe thoracic duct, or the left lymphatic duct, is the largest of the body's lymphatic ducts. It collects almost all of the lymph that circulates throughout the body (the remainder is collected by the right thoracic duct); from there, the lymph flows back into the bloodstream. The thoracic duct is a structure roughly sixteen inches long located in the mediastinum of the pleural cavity which drains lymph fluid from everywhere except the upper right quarter of the body above the diaphragm and  down the midline (this is collected by the right lymphatic duct)."
    };
    public static String[] IntegumentarySystem_value = new String[]{
            "\tis a layer of skin between the epidermis (with which it makes up the cutis) and subcutaneous tissues, that primarily consists of dense irregular connective tissue and cushions the body from stress and strain. It is divided into two layers, the superficial area adjacent to the epidermis called the papillary region and a deep thicker area known as the reticular dermis. The dermis is tightly connected to the epidermis through a basement membrane. Structural components of the dermis are collagen, elastic fibers, and extrafibrillar matrix.[2] It also contains mechanoreceptors that provide the sense of touch and thermoreceptors that provide the sense of heat. In addition, hair follicles, sweat glands, sebaceous glands, apocrine glands, lymphatic vessels and blood vessels are present in the dermis. Those blood vessels provide nourishment and waste removal for both dermal and epidermal cells.",
            "\tThe eccrine glands are sweat glands that are not connected to hair follicles. They function throughout life by responding to elevated body temperature due to environmental heat or physical exercise. These glands are common on the forehead, neck, and back, where they produce profuse sweating on hot days and when a person is physically active. They also are responsible for the moisture that may appear on the palms and soles when a person is emotionally stressed.",
            "\tis the outer of the two layers that make up the skin (or cutis), the inner layer being the dermis. It provides a barrier to infection from environmental pathogens and regulates the amount of water released from the body into the atmosphere through transepidermal water loss (TEWL). The outermost part of the epidermis is composed of stratified layers of flattened cells, that overlies a basal layer (stratum basale) composed of columnar cells arranged perpendicularly.",
            "\tis a protein filament that grows from follicles found in the dermis, or skin. Hair is one of the defining characteristics of mammals. The human body, apart from areas of glabrous skin, is covered in follicles which produce thick terminal and fine vellus hair. Most common interest in hair is focused on hair growth, hair types and hair care, but hair is also an important biomaterial primarily composed of protein, notably keratin. Attitudes towards different hair, such as hairstyles and hair removal, vary widely across different cultures and historical periods, but it is often used to indicate a person's personal beliefs or social position, such as their age, sex, or religion.",
            "\tA hair follicle is a group of epidermal cells at the base of a tube-like depression. Hair is present on all skin surfaces except the palms, soles, lips, nipples, and various parts of the external reproductive organs; however, it is not always well developed. For example, it is very fine on the forehead and the inside surface of the arm. Each hair develops from a hair follicle. This follicle extends from the surface into the dermis and may pass into the subcutaneous layer.",
            "\tA nerve, also known as a sensory neuron, comes from every part of the body to carry impulses to the brain or spinal cord concerning the condition of every nook and cranny in the body, including the muscles. Within the body the nerves branch out like telephone wires from an exchange. They run to every part of the body, from the soles of the feet to the top of the scalp and from just below the skin to the inner organs such as the heart, liver and lungs.",
            "\tThe sebaceous gland is part of the holocrine glands (glands that release entire cells filled with secretory products). The cells of the sebaceous glands produce globules of a fatty material that accumulates, causing the cells to swell and burst. The resulting mixture of fatty material and cellular debris is called sebum.",
            "\tThe skin is by far the largest organ of the human body, weighing about 10 pounds (4.5 kg) and measuring about 20 square feet (2 square meters) in surface area. It forms the outer covering for the entire body and protects the internal tissues from the external environment.",
            "-\tThe subcutis layer is one of three integrated layers of the skin. It is joined to the bottom of the dermis (the second layer) and is the deepest layer of the skin. It contains lipocytes, which produce lipids for the subcutaneous tissue to make a fatty layer that cushions muscles, bones and inner organs against shocks, and acts as an insulator and source of energy during lean times."
    };
    public static String[] NervousSystem_value = new String[]{
            "\tThe brain is one of the most complex and magnificent organs in the human body. Our brain gives us awareness of ourselves and of our environment, processing a constant stream of sensory data. It controls our muscle movements, the secretions of our glands, and even our breathing and internal temperature. Every creative thought, feeling, and plan is developed by our brain. The brain’s neurons record the memory of every event in our lives.",
            "\tis one of thirty-one pairs of spinal nerves that originate from the spinal cord and the uppermost of the lumbar nerves in the lower back. Although spinal nerves do not have individual names, they are grouped according to the level from which they stem, and each nerve is numbered in sequence. Hence, there are five pairs of lumbar nerves (L1 - L5).",
            "\tThe plantar digital nerves of the great toes stem from the common digital nerve, pierce the plantar aponeurosis and send a branch to the flexor hallucis brevis. They are also distributed to the skin on the inside of the big toe.",
            "\tis one of thirty-one pairs of spinal nerves that originate from the spinal cord and the uppermost of the sacral nerves in the pelvis. Although spinal nerves do not have individual names, they are grouped according to the level from which they stem, and each nerve is numbered in sequence. Hence, there are five pairs of sacral nerves (S1 - S5).",
            "\tThe saphenous nerve is the largest and longest branch of the femoral nerve; it supplies the skin on the inside of the leg.",
            "\tThe sciatic nerve is the largest and longest spinal nerve in the human body. Extending from the lumbar and sacral plexuses in the lower back, the sciatic nerve runs through the buttocks and into the thighs. It delivers nerve signals to and from the muscles and skin of the thighs, lower legs and feet.",
            "\tThe spinal cord is a major component of the central nervous system (CNS) that forms the vital link between the brain and most of the body. Its 31 spinal segments connect the CNS to the organs and tissues of the neck, torso, and limbs. The spinal cord also performs important processing functions to maintain balance and respond quickly to stimuli.",
            "\tThe sural nerve (short saphenous nerve) lies with the small saphenous vein. It supplies the branches to the skin on the back of the leg and then continues as the lateral dorsal cutaneous nerve along the outside of the foot and little toe.",
            "\tThoracic nerve is one of thirty-one pairs of spinal nerves that originate from the spinal cord and the uppermost of the twelve (12) thoracic nerves of the torso. Although spinal nerves do not have individual names, they are grouped according to the level from which they stem, and each nerve is numbered in sequence. Hence, there are twelve pairs of thoracic nerves (T1 - T12)."
    };

    public static String[] ReproductiveSystem_female_value = new String[]{
            "\tIn the anatomy of the female reproductive system, the cervical canal (also called the canal of the cervix, endocervical canal, cervical canal of uterus, or the cavity of cervix) is the spindle-shaped, flattened canal of the cervix, the neck of the uterus.\n" +
                    "\t\tIt communicates with the uterine cavity via the internal orifice of the uterus (or internal os), and with the vagina via the external orifice of the uterus (ostium of uterus or external os). The internal orifice of the uterus is an interior narrowing of the uterine cavity. It corresponds to a slight constriction known as the isthmus that can be seen on the surface of the uterus about midway between the apex and base. The external orifice of the uterus is a small, depressed, somewhat circular opening on the rounded extremity of the cervix, opening to the vagina. Through this aperture, the cervical cavity communicates with that of the vagina.\n" +
                    "\tThe external orifice is bounded by two lips, an anterior and a posterior. The anterior is shorter and thicker, though it projects lower than the posterior because of the slope of the cervix. Normally, both lips are in contact with the posterior vaginal wall. Prior to pregnancy the external orifice has a rounded shape when viewed through the vaginal canal (as through a speculum). Following parturition, the orifice takes on an appearance more like a transverse slit or is \"H-shaped\".\n" +
                    "\tThe wall of the canal presents an anterior and a posterior longitudinal ridge, from each of which proceed a number of small oblique columns, the palmate folds, giving the appearance of branches from the stem of a tree; to this arrangement the name arbor vitae uteri is applied.\n" +
                    "\tThe folds on the two walls are not exactly opposed, but fit between one another so as to close the cervical canal.",
            "\tis the inner epithelial layer, along with its mucous membrane, of the mammalian uterus. It has a basal layer and a functional layer; the functional layer thickens and then is sloughed during the menstrual cycle or estrous cycle. During pregnancy, the glands and blood vessels in the endometrium further increase in size and number. Vascular spaces fuse and become interconnected, forming the placenta, which supplies oxygen and nutrition to the embryo and fetus. The presence of commensal bacteria in the uterus and endometrium has been identified.",
            "\talso known as, uterine tubes, and salpinges (singular salpinx), are two very fine tubes lined with ciliatedepithelia, leading from the ovaries of female mammals into the uterus, via the uterotubal junction. In non-mammalian vertebrates, the equivalent structures are called oviducts.",
            "\tThe fundus of the uterus is the top portion, opposite from the cervix. Fundal height, measured from the top of the pubic bone, is routinely measured in pregnancy to determine growth rates. If the measurement is smaller or larger than what would be expected for gestational age, it can be a crude indicator of an abnormality (for example, a breech or sideways presentation, twins, or a placental issue), requiring further tests such as ultrasound to determine the exact nature of the problem, if any",
            "\t(also called the utero-ovarian ligament or proper ovarian ligament) is a fibrous ligament that connects the ovary to the lateral surface of the uterus. This ligament should not be confused with the suspensory ligament of the ovary, which extends from the ovary in the other direction.",
            "\tis an ovum-producing reproductive organ, often found in pairs in the female as part of the vertebrate female reproductive system. Birds have only one functional ovary (the left), while the other remains vestigial. Ovaries in females are analogous to testes in males, in that they are both gonads and endocrine glands. Although ovaries occur in a wide variety of animals, both vertebrate and invertebrate, this article is primarily about human ovaries.",
            "\tis a major female hormone-responsive reproductive sex organ of humans and most other mammals. In the human, the lower end of the uterus, the cervix, opens into the vagina, while the other end the fundus is connected to the fallopian tubes. It is within the uterus that the fetus develops during gestation. In the embryo the uterus develops from the paramesonephric ducts which fuse into the single organ known as a simplex uterus. The uterus has different forms in many other animals and in some it exists as two separate uteri known as a duplex uterus.",
            "\tis a muscular and tubular part of the female genital tract, which in humans extends from the vulva to the cervix. The outer vaginal opening may be partly covered by a membrane called the hymen. At the deep end, the cervix (neck of the uterus) bulges into the vagina. The vagina allows for sexual intercourse and childbirth, and channels menstrual flow, which occurs periodically as part of the menstrual cycle. The vagina has been studied in humans more than it has been in other animals. Its location and structure varies among species, and may vary in size within the same species. Unlike mammalian males, who usually have the external urethral opening as the only opening for urination and reproduction, mammalian females usually have the urethral opening for urination and the vaginal opening for the genital tract. The vaginal opening is much larger than the nearby urethral opening, and both are protected by the labia in humans. In amphibians, birds, reptiles and monotremes, the cloaca is the single external opening for the gastrointestinal tract and the urinary and reproductive tracts.",
    };
    public static String[] ReproductiveSystem_male_value = new String[]{
            "\tis a tube that connects a testicle to a vas deferens in the male reproductive system. It is present in all male reptiles, birds, and mammals. It is a single, narrow, tightly-coiled tube (in adult humans, six to seven feet in length) connecting the efferent ducts from the rear of each testicle to its vas deferens.",
            "\tis an external male intromittent organ that additionally serves as the urinal duct. The main parts are the root (radix); the body (corpus); and the epithelium of the penis including the shaft skin and the foreskin covering the glans penis. The body of the penis is made up of three columns of tissue: two corpora cavernosa on the dorsal side and corpus spongiosum between them on the ventral side. The human male urethra passes through the prostate gland, where it is joined by the ejaculatory duct, and then through the penis. The urethra traverses the corpus spongiosum, and its opening, the meatus (/miːˈeɪtəs/), lies on the tip of the glans penis. It is a passage both for urination and ejaculation of semen.\nMost of the penis develops from the same tissue in the embryo as does the clitoris in females; the skin around the penis and the urethra come from the same embryonic tissue from which develops the labia minora in females.[1][2] An erection is the stiffening and rising of the penis, which occurs during sexual arousal, though it can also happen in non-sexual situations. The most common form of genital alteration is circumcision, removal of part or all of the foreskin for various cultural, religious and, more rarely, medical reasons. There is controversy surrounding circumcision.\nWhile results vary across studies, the consensus is that the average erect human penis is approximately 12.9–15 cm (5.1–5.9 in) in length with 95% of adult males falling within the interval 10.7–19.1 cm (4.2–7.5 in). Neither age nor size of the flaccid penis accurately predicts erectile length.",
            "\tis a compound tubuloalveolar exocrine gland of the male reproductive system in most mammals. It differs considerably among species anatomically, chemically, and physiologically.\nThe function of the prostate is to secrete a slightly alkaline fluid, milky or white in appearance, that in humans usually constitutes roughly 30% of the volume of the semen along with spermatozoa and seminal vesicle fluid.[4] Semen is made alkaline overall with the secretions from the other contributing glands, including, at least, the seminal vesicle fluid. The alkalinity of semen helps neutralize the acidity of the vaginal tract, prolonging the lifespan of sperm. The prostatic fluid is expelled in the first ejaculate fractions, together with most of the spermatozoa. In comparison with the few spermatozoa expelled together with mainly seminal vesicular fluid, those expelled in prostatic fluid have better motility, longer survival and better protection of the genetic material.\nThe prostate also contains some smooth muscles that help expel semen during ejaculation.",
            "\tvesicular glands, or seminal glands, are a pair of simple tubular glands posteroinferior to the urinary bladder of some male mammals. Seminal vesicles are located within the pelvis. They secrete fluid that partly composes the semen.",
            "\tis the male gonad in animals. Like the ovaries to which they are homologous, the testicles (testes) are components of both the reproductive system and the endocrine system. The primary functions of the testes are to produce sperm (spermatogenesis) and to produce androgens, primarily testosterone.\nBoth functions of the testicle are influenced by gonadotropic hormones produced by the anterior pituitary. Luteinizing hormone (LH) results in testosterone release. The presence of both testosterone and follicle-stimulating hormone (FSH) is needed to support spermatogenesis. It has also been shown in animal studies that if testes are exposed to either too high or too low levels of estrogens (such as estradiol; E2) spermatogenesis can be disrupted to such an extent that the animals become infertile.",
            "\talso called ductus deferens,  is part of the male reproductive system of many vertebrates; these vasa transport sperm from the epididymis to the ejaculatory ducts in anticipation of ejaculation."
    };
    public static String[] RespiratorySystem_value = new String[]{
            "\tThe diaphragm in the respiratory system is the dome-shaped sheet of muscle that separates the chest from the abdomen. It is also referred to the thoracic diaphragm because it’s located in the thoracic cavity, or chest. It is attached to the spine, ribs and sternum and is the main muscle of respiration, playing a very important role in the breathing process. The lungs are enclosed in a kind of cage in which the ribs form the sides and the diaphragm, an upwardly arching sheet of muscle forms the floor. When we breathe, the diaphragm is drawn downward until it is flat. At the same time, the muscles around the ribs pull them up like a hoop skirt. The chest, or thoracic, cavity becomes deeper and larger, making more air space.",
            "\tThe frontal sinus is located in the frontal bone above each eye. They are air spaces lined with mucous membranes and located above each orbit.",
            "\tThe larynx is a tough, flexible segment of the respiratory tract connecting the pharynx to the trachea in the neck. It plays a vital role in the respiratory tract by allowing air to pass through it while keeping food and drink from blocking the airway. The larynx is also the body’s “voice box” as it contains the vocal folds that produce the sounds of speech and singing.",
            "\tThe human lungs are a pair of large, spongy organs optimized for gas exchange between our blood and the air. Our bodies require oxygen in order to survive. The lungs provide us with that vital oxygen while also removing carbon dioxide before it can reach hazardous levels.",
            "\tThe maxillary sinus, also known as the antrum of Highmore, is the largest of the sinuses--air-filled spaces that extend from the floor of the orbits to the roots of the upper teeth..",
            "\tAlso known as the oral cavity, the mouth is the hollow cavity that allows food and air to enter the body. The mouth contains many other organs - such as the teeth, tongue, and the ducts of the salivary glands - that work together to aid in the ingestion and digestion of food. The mouth also plays a major role in the production of speech through the movements of the tongue, lips and cheeks.",
            "\tThe nasopharynx is located above the soft palate. It communicates with the nasal cavity and provides a passageway for air during breathing. The eustachian tubes, which connect the pharynx with the middle ears, open through the walls of the nasopharynx.",
            "\tThe oropharynx, or pharynx, is a passage that connects the back of the mouth and the nose to the esophagus. This muscular tube, which is lined with mucous membranes, is a part of the respiratory and the digestive systems. The top section of the pharynx is an air passage that connects the nasal cavity to the region behind the soft palate of the mouth. The middle section is a passage for both air and food and ends below the tongue. The lowest section is for food only and lies behind and to each side of the larynx, or voice box, merging with the esophagus. The average person breathes in about 13 million cubic feet of air in a lifetime. The air coming from a sneeze may reach a speed of 100 miles per hour.",
            "\tThe trachea (or windpipe) is a wide, hollow tube that connects the larynx (or voice box) to the bronchi of the lungs. It is an integral part of the body’s airway and has the vital function of providing air flow to and from the lungs for respiration.",
    };

    public static String[] SkeletalSystem_value = new String[]{
            "\tThe calcaneus, or heel bone, is the largest of the ankle bones, or tarsus. It is located below the talus where it projects backward to form the base of the heel. It helps to support the weight of the body and provides an attachment for muscles that move the foot.",
            "\tThe clavicles, or collarbones, are a pair of long bones that connect the scapula to the sternum. The name clavicle comes from the Latin word for “little key” and describes the shape of the clavicle as an old-fashioned skeleton key. The clavicle is one of the most commonly broken bones in the human body. It also serves as an important and easily located bony landmark due to its superficial location and projection from the trunk.",
            "\tThe cuboid bone is one of the seven bones that make up the tarsus, or ankle bones.",
            "\tThe false ribs are the remaining five pairs of ribs (the other seven are called true ribs) in which their cartilages do not reach the sternum directly. Instead, the cartilages of the upper three false ribs join the cartilages attached to the ribs above.",
            "\tThe fibula is the long, thin and lateral bone of the lower leg. It runs parallel to the tibia, or shin bone, and plays a significant role in stabilizing the ankle and supporting the muscles of the lower leg. Compared to the tibia, the fibula is about the same length, but is considerably thinner. The difference in thickness corresponds to the varying roles of the two bones; the tibia bears the body’s weight from the knees to the ankles, while the fibula merely functions as a support for the tibia. At the fibula’s proximal end, just below the knee, is a slightly ",
            "\tThe hamate bone is located in the wrist, and can be identified by its wedged shape. It is situated above the fourth and fifth fingers. This bone is generally the one fractured when golfers swing and miss their ball, striking the ground with considerable downward force.",
            "\tThe humerus is the both the largest bone in the arm and the only bone in the upper arm. Many powerful muscles that manipulate the upper arm at the shoulder and the forearm at the elbow are anchored to the humerus. Movement of the humerus is essential to all of the varied activities of the arm, such as throwing, lifting, and writing.",
            "\tThe ilium is the largest and most superior of the three bones that join to form the hipbone, or os coxa. It is a wide, flat bone that provides many attachment points for muscles of the trunk and hip. You can find the crest of your ilium by placing your hands on your hips. The superficial location of the ilium makes it a common site for extracting bone tissue for grafting and bone marrow for transplants.",
            "\tThe lunate bone is one of the eight small carpal bones in the wrist that are firmly bound in two rows of four bones each. It's located on the upper end of the wrist, where it connects with ligaments and the lower arm bones.",
            "\tThe metatarsal bones are five long, cylindrical bones in the foot. The bones make up the central skeleton of the foot and are held in an arch formation by surrounding ligaments. The metatarsal bones are joined to the toe bones at the metatarsophalangeal joint, or the knuckles on the toes.",
            "\tThe navicular bone is one of the seven tarsal, or ankle, bones. This bone, along with the other tarsal bones, forms a group called the tarsus.",
            "\tThe patella is the technical name for the kneecap, the triangular-shaped bone at the front of the knee joint. The patella is held in place by muscles, the lower end of which surrounds the patella and is then attached to the upper part of the tibia (shin) by patellar tendons. The patella protects the knee joint.",
            "\tThe radius is the more lateral and slightly shorter of the two forearm bones. It is found on the thumb side of the forearm and rotates to allow the hand to pivot at the wrist. Several muscles of the arm and forearm have origins and insertions on the radius to provide motion to the upper limb. These movements are essential to many everyday tasks such as writing, drawing, and throwing a ball.",
            "\tThe scaphoid bone is one of the eight small carpal bones in the wrist that are firmly bound in two rows of four bones each. It's located on the upper end of the wrist, where it connects with ligaments and the lower arm bones.",
            "\tThe scapula is the technical name for the shoulder blade. It is a flat, triangular bone that lies over the back of the upper ribs. The rear surface can be felt under the skin. It serves as an attachment for some of the muscles and tendons of the arm, neck, chest and back and aids in the movements of the arm and shoulder. It is well padded with muscle so that great force is required to fracture it. The back surface of each scapula is divided into unequal portions by a spine.",
            "\tA collection of 22 bones, the skull protects the all-important brain and supports the other soft tissues of the head. During fetal development, the bones of the skull form within tough, fibrous membranes in a fetus’ head. As these bones grow throughout fetal and childhood development, they begin to fuse together, forming a single skull. The only bone that remains separate from the rest of the skull is the mandible, or jaw bone. Early separation of the bones provides the fetal skull with the flexibility necessary to pass through the tight confines of the birth canal during childhood development, the skull bones remain somewhat separated, allowing for growth of the brain and skull. Upon reaching maturity, our skull bones fuse to produce a rigid protective shell for the soft nervous tissue of our brain.",
            "\tStretching down the midline of the trunk from the base of the skull to the coccyx, the spine plays an extremely important role in our bodies as it supports the upper body’s weight; provides posture while allowing for movement and flexibility; and protects the spinal cord.",
            "\tThe sternum, commonly known as the breastbone, is a long, narrow flat bone that serves as the keystone of the rib cage and stabilizes the thoracic skeleton. Several muscles that move the arms, head, and neck have their origins on the sternum. It also protects several vital organs of the chest, such as the heart, aorta, vena cava, and thymus gland that are located just deep to the sternum.",
            "\tThe talus is a tarsal bone and is arranged with a group, called the tarsus, so that it can move freely where it joins the tibia and fibula (lower leg bones). This is known as the head of the talus.",
            "\tThe teeth are a group of hard organs found in the oral cavity. We use teeth to masticate (or chew) food into tiny pieces. They also provide shape to the mouth and face and are important components in producing speech.",
            "\tThe tibia, sometimes known as the shin bone, is the larger and stronger of the two lower leg bones. It forms the knee joint with the femur and the ankle joint with the fibula and tarsus. Many powerful muscles that move the foot and lower leg are anchored to the tibia. The support and movement of the tibia is essential to many activities performed by the legs, including standing, walking, running, jumping and supporting the body’s weight.",
            "\tThe true ribs are attached to the sternum (breastbone) directly by their costal cartilages. There are seven true ribs. (The other ribs are termed floating or false ribs.)",
            "\tThe ulna is the longer, larger and more medial of the lower arm bones. Many muscles in the arm and forearm attach to the ulna to perform movements of the arm, hand and wrist. Movement of the ulna is essential to such everyday functions as throwing a ball and driving a car.",
    };

    public static String[] UrinarySystem_value = new String[]{
            "-\tare two bean-shaped organs found on the left and right sides of the body in vertebrates. They filter the blood in order to make urine, to release and retain water, and to remove waste. They also control the ion concentrations and acid-base balance of the blood. Each kidney feeds urine into the bladder by means of a tube known as the ureter.\n" +
                    "The kidneys regulate the balance of ions known as electrolytes in the blood, along with maintaining acid base homeostasis. They also move waste products out of the blood and into the urine, such as nitrogen-containing urea and ammonium. Kidneys also regulate fluid balance and blood pressure. They are also responsible for the reabsorption of water, glucose, and amino acids. The kidneys also produce hormones including calcitriol and erythropoietin. The kidneys also make an important enzyme, renin, which affects blood pressure through negative feedback.\n" +
                    "Located at the rear of the abdominal cavity in the retroperitoneal space, the kidneys receive blood from the paired renal arteries, and drain into the paired renal veins.\n",
            "-\tIn human anatomy, the ureters are tubes made of smooth muscle fibers that propel urine from the kidneys to the urinary bladder. In the adult, the ureters are usually 25–30 cm (10–12 in) long and ~3–4 mm in diameter. Histologically, the ureter contains transitional epithelium and an additional smooth muscle layer in the more distal one-third to assist with peristalsis.",
            "-\tis a tube that connects the urinary bladder to the urinary meatus for the removal of fluids from the body. In male placental mammals, the urethra travels through the penis, and carries semen as well as urine. In female placental mammals, the urethra is shorter and emerges at the female external urethral orifice above the vaginal opening.",
            "-\t is a hollow muscular organ that collects urine from the kidneys before disposal by urination. A hollow muscular, and distensible (or elastic) organ, the bladder sits on the pelvic floor. Urine enters the bladder via the ureters and exits via the urethra. The typical human bladder capacity is between 300 and 500 mL (10.14 and 16.91 fl oz)."};
}
